const { default: expect } = require("expect")
const { getTenEconomincalBowler } = require("../src/server/4-top-ten-economical-bowler")


const matches = [
    {
    id: '1',
    season: '2015',
    city: 'Chandigarh',
    date: '2015-05-16',
    team1: 'Kings XI Punjab',
    team2: 'Chennai Super Kings',
    toss_winner: 'Kings XI Punjab',
    toss_decision: 'bat',
    result: 'normal',
    dl_applied: '0',
    winner: 'Chennai Super Kings',
    win_by_runs: '0',
    win_by_wickets: '7',
    player_of_match: 'P Negi',
    venue: 'Punjab Cricket Association Stadium, Mohali',
    umpire1: 'CK Nandan',
    umpire2: 'C Shamshuddin',
    umpire3: ''
  },
  {
    id: '1',
    season: '2015',
    city: 'Mumbai',
    date: '2015-05-16',
    team1: 'Rajasthan Royals',
    team2: 'Kolkata Knight Riders',
    toss_winner: 'Rajasthan Royals',
    toss_decision: 'bat',
    result: 'normal',
    dl_applied: '0',
    winner: 'Rajasthan Royals',
    win_by_runs: '9',
    win_by_wickets: '0',
    player_of_match: 'SR Watson',
    venue: 'Brabourne Stadium',
    umpire1: 'RM Deshpande',
    umpire2: 'RK Illingworth',
    umpire3: ''
  },
  {
    id: '1',
    season: '2015',
    city: 'Bangalore',
    date: '2015-05-17',
    team1: 'Delhi Daredevils',
    team2: 'Royal Challengers Bangalore',
    toss_winner: 'Royal Challengers Bangalore',
    toss_decision: 'field',
    result: 'no result',
    dl_applied: '0',
    winner: '',
    win_by_runs: '0',
    win_by_wickets: '0',
    player_of_match: '',
    venue: 'M Chinnaswamy Stadium',
    umpire1: 'HDPK Dharmasena',
    umpire2: 'K Srinivasan',
    umpire3: ''
  },
  {
    id: '1',
    season: '2015',
    city: 'Hyderabad',
    date: '2015-05-17',
    team1: 'Sunrisers Hyderabad',
    team2: 'Mumbai Indians',
    toss_winner: 'Sunrisers Hyderabad',
    toss_decision: 'bat',
    result: 'normal',
    dl_applied: '0',
    winner: 'Mumbai Indians',
    win_by_runs: '0',
    win_by_wickets: '9',
    player_of_match: 'MJ McClenaghan',
    venue: 'Rajiv Gandhi International Stadium, Uppal',
    umpire1: 'CB Gaffaney',
    umpire2: 'K Srinath',
    umpire3: ''
  },
  {
    id: '2',
    season: '2015',
    city: 'Mumbai',
    date: '2015-05-19',
    team1: 'Mumbai Indians',
    team2: 'Chennai Super Kings',
    toss_winner: 'Mumbai Indians',
    toss_decision: 'bat',
    result: 'normal',
    dl_applied: '0',
    winner: 'Mumbai Indians',
    win_by_runs: '25',
    win_by_wickets: '0',
    player_of_match: 'KA Pollard',
    venue: 'Wankhede Stadium',
    umpire1: 'HDPK Dharmasena',
    umpire2: 'RK Illingworth',
    umpire3: ''
  },
  {
    id: '2',
    season: '2015',
    city: 'Pune',
    date: '2015-05-20',
    team1: 'Royal Challengers Bangalore',
    team2: 'Rajasthan Royals',
    toss_winner: 'Royal Challengers Bangalore',
    toss_decision: 'bat',
    result: 'normal',
    dl_applied: '0',
    winner: 'Royal Challengers Bangalore',
    win_by_runs: '71',
    win_by_wickets: '0',
    player_of_match: 'AB de Villiers',
    venue: 'Maharashtra Cricket Association Stadium',
    umpire1: 'AK Chaudhary',
    umpire2: 'C Shamshuddin',
    umpire3: ''
  },
  {
    id: '2',
    season: '2015',
    city: 'Ranchi',
    date: '2015-05-22',
    team1: 'Royal Challengers Bangalore',
    team2: 'Chennai Super Kings',
    toss_winner: 'Chennai Super Kings',
    toss_decision: 'field',
    result: 'normal',
    dl_applied: '0',
    winner: 'Chennai Super Kings',
    win_by_runs: '0',
    win_by_wickets: '3',
    player_of_match: 'A Nehra',
    venue: 'JSCA International Stadium Complex',
    umpire1: 'AK Chaudhary',
    umpire2: 'CB Gaffaney',
    umpire3: ''
  },
  {
    id: '3',
    season: '2016',
    city: 'Kolkata',
    date: '2015-05-24',
    team1: 'Mumbai Indians',
    team2: 'Chennai Super Kings',
    toss_winner: 'Chennai Super Kings',
    toss_decision: 'field',
    result: 'normal',
    dl_applied: '0',
    winner: 'Mumbai Indians',
    win_by_runs: '41',
    win_by_wickets: '0',
    player_of_match: 'RG Sharma',
    venue: 'Eden Gardens',
    umpire1: 'HDPK Dharmasena',
    umpire2: 'RK Illingworth',
    umpire3: ''
  }
]

const deliveries = [
    {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '18',
        ball: '4',
        batsman: 'STR Binny',
        non_striker: 'Sachin Baby',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '0',
        extra_runs: '0',
        total_runs: '0',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '18',
        ball: '5',
        batsman: 'STR Binny',
        non_striker: 'Sachin Baby',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '1',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '0',
        extra_runs: '1',
        total_runs: '1',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '18',
        ball: '6',
        batsman: 'Sachin Baby',
        non_striker: 'STR Binny',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '4',
        extra_runs: '0',
        total_runs: '4',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '19',
        ball: '1',
        batsman: 'STR Binny',
        non_striker: 'Sachin Baby',
        bowler: 'Mustafizur Rahman',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '1',
        extra_runs: '0',
        total_runs: '1',
        player_dismissed: 'STR Binny',
        dismissal_kind: 'run out',
        fielder: 'DJ Hooda'
      },
      {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '19',
        ball: '2',
        batsman: 'CJ Jordan',
        non_striker: 'Sachin Baby',
        bowler: 'Mustafizur Rahman',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '2',
        extra_runs: '0',
        total_runs: '2',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '19',
        ball: '3',
        batsman: 'CJ Jordan',
        non_striker: 'Sachin Baby',
        bowler: 'Mustafizur Rahman',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '0',
        extra_runs: '0',
        total_runs: '0',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '19',
        ball: '4',
        batsman: 'CJ Jordan',
        non_striker: 'Sachin Baby',
        bowler: 'Mustafizur Rahman',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '1',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '0',
        extra_runs: '1',
        total_runs: '1',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '1',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '19',
        ball: '5',
        batsman: 'Sachin Baby',
        non_striker: 'CJ Jordan',
        bowler: 'Mustafizur Rahman',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '2',
        extra_runs: '0',
        total_runs: '2',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '2',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '19',
        ball: '6',
        batsman: 'Sachin Baby',
        non_striker: 'CJ Jordan',
        bowler: 'Mustafizur Rahman',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '6',
        extra_runs: '0',
        total_runs: '6',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '2',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '20',
        ball: '1',
        batsman: 'CJ Jordan',
        non_striker: 'Sachin Baby',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '1',
        extra_runs: '0',
        total_runs: '1',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '2',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '20',
        ball: '2',
        batsman: 'Sachin Baby',
        non_striker: 'CJ Jordan',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '2',
        extra_runs: '0',
        total_runs: '2',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '2',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '20',
        ball: '3',
        batsman: 'Sachin Baby',
        non_striker: 'CJ Jordan',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '0',
        extra_runs: '0',
        total_runs: '0',
        player_dismissed: 'CJ Jordan',
        dismissal_kind: 'run out',
        fielder: 'NV Ojha'
      },
      {
        match_id: '2',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '20',
        ball: '4',
        batsman: 'Iqbal Abdulla',
        non_striker: 'Sachin Baby',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '1',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '0',
        extra_runs: '1',
        total_runs: '1',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '2',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '20',
        ball: '5',
        batsman: 'Sachin Baby',
        non_striker: 'Iqbal Abdulla',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '1',
        extra_runs: '0',
        total_runs: '1',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      },
      {
        match_id: '3',
        inning: '2',
        batting_team: 'Royal Challengers Bangalore',
        bowling_team: 'Sunrisers Hyderabad',
        over: '20',
        ball: '6',
        batsman: 'Iqbal Abdulla',
        non_striker: 'Sachin Baby',
        bowler: 'B Kumar',
        is_super_over: '0',
        wide_runs: '0',
        bye_runs: '0',
        legbye_runs: '0',
        noball_runs: '0',
        penalty_runs: '0',
        batsman_runs: '4',
        extra_runs: '0',
        total_runs: '4',
        player_dismissed: '',
        dismissal_kind: '',
        fielder: ''
      }
    ]

const expected = [{"bowler": "B Kumar", "economyRate": "1.25"}, {"bowler": "Mustafizur Rahman", "economyRate": "2.00"}]


test('Returns the top ten economical bowlers', () => {
    expect(getTenEconomincalBowler(matches, deliveries)).toEqual(expected)
})